### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by bobbymannino** [Rawnly/raycast-music#2]
It loads the page with the red button saying authenticate and then clicking the button does nothing, no error is console logged either so not sure if anything is happening

**Comment by rawnly** [comment]
Can you try this page?

https://raycast-music-git-1-authentication-error-fedevitaledev.vercel.app/auth

**Comment by bobbymannino** [comment]
```
MusicKit Script Loaded
(4) MusicKit has been initialized
```

Just comes up with that in the console log. but everytime i click the button the second line gets logged again.

If it means anything i am on M1 Mac Mini

**Comment by rawnly** [comment]
Do you have some pop-up blocks or something similar? Unfortunately the authentication is all managed by the library made by Apple 🥲

I can't do more than initialise the class and call the authorize() method.

This should open a new tab and then come back to the current one with the token once the flow is completed

**Comment by rawnly** [comment]
Code is available here https://github.com/Rawnly/raycast-music.app/blob/1-authentication-error/src/app/auth/page.tsx

**Comment by bobbymannino** [comment]
ive tried it in Arc, Safari & Edge. not working, also turned off security completely and all ad blockers etc. still nothing. on line 65 i would assume that no instance is created so its returning as im not getting either code from try catch block (which means its stopping before them). if instance is not defined that is because line 43 i would say. ill have a mess around on my side and see if i come up with anything

**Comment by rawnly** [comment]
Unfortunately I'm not able to reproduce this 🙁

On my side everything works so I'm not sure what to do now. I'll try deploying a static page later

**Comment by mirkopoloni** [comment]
Same problem as @bobbymannino, but I am using an intel MacBook, so the M1 shouldn't be the problem.
macOS: Ventura 13.1
Tried with Arc and Safari.
Let me know if I can help you somehow, I haven't debugged the code locally but I can do it if you think this could help.

**Comment by rawnly** [comment]
Ok I found the problem (i think) there was an issue with the initialization of the MusicKit instance. It should be fixed in the new deployment

**Comment by rawnly** [comment]
> Can you try this page?
> 
> [raycast-music-git-1-authentication-error-fedevitaledev.vercel.app/auth](https://raycast-music-git-1-authentication-error-fedevitaledev.vercel.app/auth)

This should be working now

**Comment by mirkopoloni** [comment]
> > Can you try this page?
> > [raycast-music-git-1-authentication-error-fedevitaledev.vercel.app/auth](https://raycast-music-git-1-authentication-error-fedevitaledev.vercel.app/auth)
> 
> This should be working now

Thanks, the redirect to the apple login is working but the authentication still doesn't work.
<img width="430" alt="Screenshot 2023-04-14 at 19 47 19" src="https://user-images.githubusercontent.com/32099118/232119752-bbcb005d-a43d-441d-b135-89ec9aedc04c.png">

**Comment by Rawnly** [comment]
Ok can you check the console? @mirkopoloni

**Comment by rawnly** [comment]
Ok, I can reproduce this, I think the issue is server-side (apple). The server responds 401 and 403 when the library tries to request the token :/

**Comment by rawnly** [comment]
@mirkopoloni can you try again? Now it worked for me

**Comment by mirkopoloni** [comment]
> @mirkopoloni can you try again? Now it worked for me

@Rawnly Still not working unfortunately 
<img width="2030" alt="Screenshot 2023-04-14 at 20 06 07" src="https://user-images.githubusercontent.com/32099118/232123258-dcf51712-567a-48dc-969c-d14e9cc7e80e.png">

**Comment by rawnly** [comment]
oh i'm so dumb, i got the problem. the token is encrypted with only some issuers allowed :/, let me deploy on main branch

**Comment by rawnly** [comment]
Just tried "https://raycast-music.app" works for me

**Comment by mirkopoloni** [comment]
It works 😄 thanks
<img width="927" alt="Screenshot 2023-04-14 at 20 18 43" src="https://user-images.githubusercontent.com/32099118/232125480-0106a044-c7a3-4f6b-b3f4-d21f576c9217.png">

**Comment by bobbymannino** [comment]
This all works for me now too. so if your happy to you can close the issue successfully
